### PR TITLE
Use accept-language in locale view

### LINKED ISSUE #25: Feature Request: Autofill locale while missing in page url
Allow such as: https://l10n.mozilla-community.org/~pascalc/stores_l10n/locale/apple/release/.
Order: user's browser preferences, fallback (en-US).

This allows greater flexibility to files's comment.

### PR DESCRIPTION
**Pull request by flodolo**
Fixes #25

### CODE REVIEW

**Comment by yfdyh000** [comment]
This implementation seems differs from AMO and other sites in that they are redirected to the appropriate locale.

**Comment by flodolo** [comment]
That wasn't my plan: it seems reasonable to show the content instead of redirecting. 
The same approach happens here: https://l10n.mozilla-community.org/webstatus/

**Comment by flodolo** [comment]
On second thoughts, I can see how this could be confusing, even if the locale agnostic URL is not "promoted" anywhere. I'll look into redirecting instead.

**Comment by flodolo** [comment]
Fixed in #84

**Pull request merged**
