### PR TITLE
Whatsnew content for 56 beta + new locales

### PR DESCRIPTION
**Pull request by Delphine**

### CODE REVIEW

**Comment by Delphine** [comment]
@flodolo Sure this is on your radar, but it won't let me add anyone as reviewer, so flagging you just in case :)

**Comment by flodolo** [comment]
That's weird, this repo has the same settings at others.

**Comment by flodolo** [comment]
OK, this is a bit confusing. 

This PR says that it adds new locales, but it also adds content for 55 whatsnew. This is OK (having both commits in one PR), going to amend the title.

The confusing part is the appstores content. This PR adds content for the new locales
https://github.com/mozilla-l10n/appstores/pull/97

Then you have a second PR to add content for whatsnew, but: since you changed both (new locales, whatsnew55), you're adding all the files (including da and be) in this other PR
https://github.com/mozilla-l10n/appstores/pull/98

I'm going to close the first, and use only the second. I understand it might be a bit confusing, but we can chat more on IRC.

**Comment by Delphine** [comment]
You're right it's confusing! (and I should have changed the title here after my 2nd commit, totally forgot).
Yeah let's chat more later on irc. I think I mostly get it, but want to think about it a bit more :)

**Pull request merged**
